name: Frontend Test

on:
  push:
    branches:
      - main
      - develop
      - feature/*

  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Build
        run: npm run build

      - name: Run Dev (Optional)
        run: npm run dev
