name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Build Project
        run: npm run build
        working-directory: backend

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build Project
        run: npm run build
        working-directory: frontend
